name: Test and publish

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Flake8
        run: pip install flake8
      - name: Run Flake8
        run: flake8 --max-line-length=120

  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup Poetry and dependencies
        run: |
          pip install poetry
          poetry install --no-interaction --no-root
      - name: Execute tests
        run: |
          cd src
          poetry run pytest --cov tests/

  build:
    runs-on: ubuntu-latest
    needs:
      - unit
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup Poetry and dependencies
        run: |
          pip install poetry
          poetry install --no-interaction --no-root
      - name: Build Python package
        run: |
          poetry build
          ls dist/
      - name: upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: dist
          retention-days: 3
